version: "3.8"
services:
  dcs-postgres:
    image: postgres:15.3-alpine
    container_name: rent-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rent
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rent-rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  app:
    build:
      context: .
      dockerfile: ./src/Apis/RentApi/Dockerfile
    container_name: rent-app
    restart: always
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - dcs-postgres
      - rabbitmq

networks:
  default:
    name: local-network
